name: tf_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - tensorflow-gpu
  - pip
  - pandas
  - numpy
  - matplotlib
  - selenium=3.141.0
  - beautifulsoup4
  - scikit-learn
  - statsmodels
  - tqdm
  - openpyxl
  - joblib
  - pip:
    - ferien-api
    - meteostat
